### ISSUE TITLE
Is this BAW skill applicable for BAW on cloud instance too ?

### ISSUE THREAD

**Issue by loser168** [blue-prism/IBMDigitalBusinessAutomation#1]
Hi, We were using this BAW skill for BAW on a local machine and it was working fine.

when we started using it for a BAW instance which is on cloud , we are not able to generate the csrf token. Is this skill not compatible with BAW on cloud ?

**Comment by loser168** [comment]
@EricWilson-BluePrism Can you please help us with the query ?

**Comment by EricWilson-BluePrism** [comment]
Yes, the skill is applicable to a cloud-based BAW too. Have you verified the URL and credentials you’re using with something like curl or Postman?

When you say you can get a token, do you receive an error response from BAW?

**Comment by loser168** [comment]
@EricWilson-BluePrism Thanks for the quick response. 

Have you verified the URL and credentials you’re using with something like curl or Postman?
- Yes, we tried it with both postman and curl and we were able to get the csrf_token. You can find the below screenshot for reference.

![image](https://user-images.githubusercontent.com/20659698/73721334-024d6500-474a-11ea-8f44-c1401976a1e0.png)

When you say you can’t get a token, do you receive an error response from BAW?
yes, i am able to see 404 not found error. The screenshot of inputs for skill is as below:

![image](https://user-images.githubusercontent.com/20659698/73721470-56f0e000-474a-11ea-930d-8993c494aac0.png)


The url i have used through blue prism is "https://gbssoldw-bawoc.automationcloud.ibm.com"
whereas in the postman it is something like "https://gbssoldw-bawoc.automationcloud.ibm.com/instance/services".
Previously it was working with just the server name as declared but not sure why is not happening for Cloud BAW.

Please help us in resolving this issue.

**Comment by loser168** [comment]
The error below is the one when we are passing "https://gbssoldw-bawoc.automationcloud.ibm.com":


Unexpected error Error during Web API HTTP Request
HTTP Status Code: 404
HTTP Response Content: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

When i pass the URL as "https://gbssoldw-bawoc.automationcloud.ibm.com/instance/services/csrf_token" i am seeing the below error :

Unexpected error Error during Web API HTTP Request
HTTP Status Code: 403
HTTP Response Content: {"error_message":"CWMGG0015E: The request was blocked because the IBM-CSRF-TOKEN token header is not valid.","incident_id":"4e0a638c-9a92-4a8c-91f5-37b08337c304","error_number":"CWMGG0015E"}

**Comment by EricWilson-BluePrism** [comment]
Interesting. It looks like the base URL you're trying to use may not be correct. I know when I worked on this, the URL of the BAW cloud instance I worked with was something to the effect of https://<xxxxxx>.bpm.ibmcloud.com:443/baw/dev. So the request for the csrf token would have been https://<xxxxxx>.bpm.ibmcloud.com:443/baw/dev/sysytem/login. I think the key here is the "/baw/dev" at the end. Do you have access to the Swagger Explorer on our cloud instance? That should show you exaclty what's expected for the base URL.

**Comment by loser168** [comment]
@EricWilson-BluePrism Thanks again for the quick response.

I have changed the base URL to "https://gbssoldw-bawoc.automationcloud.ibm.com/baw/dev" or "https://gbssoldw-bawoc.automationcloud.ibm.com:443/baw/dev" and i see the following error as the skill objects source isn't available I am unable to debug this further.
 
"Unexpected error The Web API action contains output parameters based on JSON data, but the response does not contain valid JSON content."


Do you have access to the Swagger Explorer on our cloud instance?

I have admin access to the cloud instance but i am new to BAW. By swagger explorer do you mean the following link ? https://www.ibm.com/support/knowledgecenter/SSLRPC/com.ibm.wbpm.bawoc.main.doc/dbaoc-apidoc/bpm-swagger-instance-dbaoc-published.json

If not can you let me know where i can find that ?

Thanks in advance

**Comment by EricWilson-BluePrism** [comment]
You can actually see the definition of the skill by looking at System -> Objects -> Web API Services. You'll see Web API entries for whichever IBM skills you've imported. When you double-click on one to open it, Blue Prism will pop up a dialog about doom-and-gloom if you change anything, but you'll be fine. ;-)

The request for a token expects a response payload that looks like this:

`{
"refresh-groups": [refresh_groups],
"requested-lifetime": [requested_lifetime]
}`

The Swagger Explorer you've linked is the main one from IBM's regular site, but you should also have access to one on your specific instance I believe. That's the one that should show you your base URL. The URL is something like this: https://host_name:port_number/bpm/explorer

**Comment by loser168** [comment]
@EricWilson-BluePrism Thanks for pointing at the skill definition, I will explore on the Blue Prism side.

The explorer thing that you meant is the RestAPI tester or these are 2 different things?Find the snapshot of the RestAPI tester below. documentation : https://www.ibm.com/support/knowledgecenter/SSV2LR/com.ibm.wbpm.bpc.doc/topics/tdev_testingrestapis.html

![image](https://user-images.githubusercontent.com/20659698/73768266-baa4f880-479e-11ea-9745-ae69b93f8bce.png)

**Comment by EricWilson-BluePrism** [comment]
Sorry for the delay. That should work to, especially if you can use Fiddler or something similar to catch the actual HTTP request. That way you'll see specifically, what base URL is being used. I think that's the only issue here is determining the correct base URL for your cloud instance.

**Comment by EricWilson-BluePrism** [comment]
Hi @loser168. Any news from your side?

**Comment by loser168** [comment]
Hi @EricWilson-BluePrism , Sorry for the delay. There was something wrong with our BAW cloud instance after a restart of that we are able to use your skill. But there is a issue while trying to invoke the service alone. Will it here soon.

**Comment by EricWilson-BluePrism** [comment]
Hi @loser168 . How are things progressing on your side? Still encountering issues, or are you good to go?

**Comment by EricWilson-BluePrism** [comment]
@loser168 it's been a while since I've heard from you. I'm going to close this issue. If you're still having problems please feel free to reopen and contact me.
